### PR TITLE
Add Mobile Support.

### PR DESCRIPTION
**Pull request by libremente**
Decorated the student view with the XBlocks_supports for multi_device
in order to solve the compatibility issue with mobile handheld devices.

@stvstnfrd @caesar2164 @caseylitton

### CODE REVIEW

**Comment by stvstnfrd** [comment]
+1

**Comment by caesar2164** [comment]
👍

**Comment by stvstnfrd** [comment]
@caesar2164 Should we look to merge this?

**Comment by stvstnfrd** [comment]
@caesar2164 I guess let's close this since we haven't really been testing it on mobile?

**Pull request closed without merging**
